# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import warnings

import grpc

from chronoqueue.api.queueservice.v1 import (
    request_response_pb2 as proto_dot_queueservice_dot_v1_dot_request__response__pb2,
)

GRPC_GENERATED_VERSION = "1.71.2"
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower

    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f"The grpc package installed is at version {GRPC_VERSION},"
        + f" but the generated code in proto/queueservice/v1/service_pb2_grpc.py depends on"
        + f" grpcio>={GRPC_GENERATED_VERSION}."
        + f" Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}"
        + f" or downgrade your generated code using grpcio-tools<={GRPC_VERSION}."
    )


class QueueServiceStub(object):
    """QueueService is the primary API for interacting with ChronoQueue.

    This service provides:
    - Queue lifecycle management
    - Message posting and consumption
    - Scheduled task automation
    - Dead letter queue handling
    - Schema-based validation

    Example - Basic message flow:
    1. CreateQueue: Set up a queue with retry/DLQ configuration
    2. PostMessage: Add messages to the queue
    3. GetNextMessage: Workers retrieve messages for processing
    4. AcknowledgeMessage: Mark message as successfully processed
    OR let lease expire → message returns to queue for retry
    5. After max_attempts exhausted → message moves to DLQ

    gRPC vs REST:
    - gRPC: Preferred for high-throughput, low-latency scenarios
    - REST: Convenient for browser/curl access, debugging, simple integrations

    Error handling:
    - Use gRPC status codes (InvalidArgument, NotFound, AlreadyExists, etc.)
    - Error details in status.Details() for validation errors
    ==================== Queue Management Operations ====================
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateQueue = channel.unary_unary(
            "/chronoqueue.api.queueservice.v1.QueueService/CreateQueue",
            request_serializer=proto_dot_queueservice_dot_v1_dot_request__response__pb2.CreateQueueRequest.SerializeToString,
            response_deserializer=proto_dot_queueservice_dot_v1_dot_request__response__pb2.CreateQueueResponse.FromString,
            _registered_method=True,
        )
        self.DeleteQueue = channel.unary_unary(
            "/chronoqueue.api.queueservice.v1.QueueService/DeleteQueue",
            request_serializer=proto_dot_queueservice_dot_v1_dot_request__response__pb2.DeleteQueueRequest.SerializeToString,
            response_deserializer=proto_dot_queueservice_dot_v1_dot_request__response__pb2.DeleteQueueResponse.FromString,
            _registered_method=True,
        )
        self.ListQueues = channel.unary_unary(
            "/chronoqueue.api.queueservice.v1.QueueService/ListQueues",
            request_serializer=proto_dot_queueservice_dot_v1_dot_request__response__pb2.ListQueuesRequest.SerializeToString,
            response_deserializer=proto_dot_queueservice_dot_v1_dot_request__response__pb2.ListQueuesResponse.FromString,
            _registered_method=True,
        )
        self.GetQueueState = channel.unary_unary(
            "/chronoqueue.api.queueservice.v1.QueueService/GetQueueState",
            request_serializer=proto_dot_queueservice_dot_v1_dot_request__response__pb2.GetQueueStateRequest.SerializeToString,
            response_deserializer=proto_dot_queueservice_dot_v1_dot_request__response__pb2.GetQueueStateResponse.FromString,
            _registered_method=True,
        )
        self.PostMessage = channel.unary_unary(
            "/chronoqueue.api.queueservice.v1.QueueService/PostMessage",
            request_serializer=proto_dot_queueservice_dot_v1_dot_request__response__pb2.PostMessageRequest.SerializeToString,
            response_deserializer=proto_dot_queueservice_dot_v1_dot_request__response__pb2.PostMessageResponse.FromString,
            _registered_method=True,
        )
        self.PostMessagesBulk = channel.unary_unary(
            "/chronoqueue.api.queueservice.v1.QueueService/PostMessagesBulk",
            request_serializer=proto_dot_queueservice_dot_v1_dot_request__response__pb2.PostMessagesBulkRequest.SerializeToString,
            response_deserializer=proto_dot_queueservice_dot_v1_dot_request__response__pb2.PostMessagesBulkResponse.FromString,
            _registered_method=True,
        )
        self.GetNextMessage = channel.unary_unary(
            "/chronoqueue.api.queueservice.v1.QueueService/GetNextMessage",
            request_serializer=proto_dot_queueservice_dot_v1_dot_request__response__pb2.GetNextMessageRequest.SerializeToString,
            response_deserializer=proto_dot_queueservice_dot_v1_dot_request__response__pb2.GetNextMessageResponse.FromString,
            _registered_method=True,
        )
        self.AcknowledgeMessage = channel.unary_unary(
            "/chronoqueue.api.queueservice.v1.QueueService/AcknowledgeMessage",
            request_serializer=proto_dot_queueservice_dot_v1_dot_request__response__pb2.AcknowledgeMessageRequest.SerializeToString,
            response_deserializer=proto_dot_queueservice_dot_v1_dot_request__response__pb2.AcknowledgeMessageResponse.FromString,
            _registered_method=True,
        )
        self.CancelMessage = channel.unary_unary(
            "/chronoqueue.api.queueservice.v1.QueueService/CancelMessage",
            request_serializer=proto_dot_queueservice_dot_v1_dot_request__response__pb2.CancelMessageRequest.SerializeToString,
            response_deserializer=proto_dot_queueservice_dot_v1_dot_request__response__pb2.CancelMessageResponse.FromString,
            _registered_method=True,
        )
        self.RenewMessageLease = channel.unary_unary(
            "/chronoqueue.api.queueservice.v1.QueueService/RenewMessageLease",
            request_serializer=proto_dot_queueservice_dot_v1_dot_request__response__pb2.RenewMessageLeaseRequest.SerializeToString,
            response_deserializer=proto_dot_queueservice_dot_v1_dot_request__response__pb2.RenewMessageLeaseResponse.FromString,
            _registered_method=True,
        )
        self.PeekQueueMessages = channel.unary_unary(
            "/chronoqueue.api.queueservice.v1.QueueService/PeekQueueMessages",
            request_serializer=proto_dot_queueservice_dot_v1_dot_request__response__pb2.PeekQueueMessagesRequest.SerializeToString,
            response_deserializer=proto_dot_queueservice_dot_v1_dot_request__response__pb2.PeekQueueMessagesResponse.FromString,
            _registered_method=True,
        )
        self.SendMessageHeartBeat = channel.unary_unary(
            "/chronoqueue.api.queueservice.v1.QueueService/SendMessageHeartBeat",
            request_serializer=proto_dot_queueservice_dot_v1_dot_request__response__pb2.SendMessageHeartBeatRequest.SerializeToString,
            response_deserializer=proto_dot_queueservice_dot_v1_dot_request__response__pb2.SendMessageHeartBeatResponse.FromString,
            _registered_method=True,
        )
        self.CreateSchedule = channel.unary_unary(
            "/chronoqueue.api.queueservice.v1.QueueService/CreateSchedule",
            request_serializer=proto_dot_queueservice_dot_v1_dot_request__response__pb2.CreateScheduleRequest.SerializeToString,
            response_deserializer=proto_dot_queueservice_dot_v1_dot_request__response__pb2.CreateScheduleResponse.FromString,
            _registered_method=True,
        )
        self.DeleteSchedule = channel.unary_unary(
            "/chronoqueue.api.queueservice.v1.QueueService/DeleteSchedule",
            request_serializer=proto_dot_queueservice_dot_v1_dot_request__response__pb2.DeleteScheduleRequest.SerializeToString,
            response_deserializer=proto_dot_queueservice_dot_v1_dot_request__response__pb2.DeleteScheduleResponse.FromString,
            _registered_method=True,
        )
        self.GetSchedule = channel.unary_unary(
            "/chronoqueue.api.queueservice.v1.QueueService/GetSchedule",
            request_serializer=proto_dot_queueservice_dot_v1_dot_request__response__pb2.GetScheduleRequest.SerializeToString,
            response_deserializer=proto_dot_queueservice_dot_v1_dot_request__response__pb2.GetScheduleResponse.FromString,
            _registered_method=True,
        )
        self.ListSchedules = channel.unary_unary(
            "/chronoqueue.api.queueservice.v1.QueueService/ListSchedules",
            request_serializer=proto_dot_queueservice_dot_v1_dot_request__response__pb2.ListSchedulesRequest.SerializeToString,
            response_deserializer=proto_dot_queueservice_dot_v1_dot_request__response__pb2.ListSchedulesResponse.FromString,
            _registered_method=True,
        )
        self.GetScheduleHistory = channel.unary_unary(
            "/chronoqueue.api.queueservice.v1.QueueService/GetScheduleHistory",
            request_serializer=proto_dot_queueservice_dot_v1_dot_request__response__pb2.GetScheduleHistoryRequest.SerializeToString,
            response_deserializer=proto_dot_queueservice_dot_v1_dot_request__response__pb2.GetScheduleHistoryResponse.FromString,
            _registered_method=True,
        )
        self.PauseSchedule = channel.unary_unary(
            "/chronoqueue.api.queueservice.v1.QueueService/PauseSchedule",
            request_serializer=proto_dot_queueservice_dot_v1_dot_request__response__pb2.PauseScheduleRequest.SerializeToString,
            response_deserializer=proto_dot_queueservice_dot_v1_dot_request__response__pb2.PauseScheduleResponse.FromString,
            _registered_method=True,
        )
        self.ResumeSchedule = channel.unary_unary(
            "/chronoqueue.api.queueservice.v1.QueueService/ResumeSchedule",
            request_serializer=proto_dot_queueservice_dot_v1_dot_request__response__pb2.ResumeScheduleRequest.SerializeToString,
            response_deserializer=proto_dot_queueservice_dot_v1_dot_request__response__pb2.ResumeScheduleResponse.FromString,
            _registered_method=True,
        )
        self.GetDLQMessages = channel.unary_unary(
            "/chronoqueue.api.queueservice.v1.QueueService/GetDLQMessages",
            request_serializer=proto_dot_queueservice_dot_v1_dot_request__response__pb2.GetDLQMessagesRequest.SerializeToString,
            response_deserializer=proto_dot_queueservice_dot_v1_dot_request__response__pb2.GetDLQMessagesResponse.FromString,
            _registered_method=True,
        )
        self.RequeueFromDLQ = channel.unary_unary(
            "/chronoqueue.api.queueservice.v1.QueueService/RequeueFromDLQ",
            request_serializer=proto_dot_queueservice_dot_v1_dot_request__response__pb2.RequeueFromDLQRequest.SerializeToString,
            response_deserializer=proto_dot_queueservice_dot_v1_dot_request__response__pb2.RequeueFromDLQResponse.FromString,
            _registered_method=True,
        )
        self.DeleteFromDLQ = channel.unary_unary(
            "/chronoqueue.api.queueservice.v1.QueueService/DeleteFromDLQ",
            request_serializer=proto_dot_queueservice_dot_v1_dot_request__response__pb2.DeleteFromDLQRequest.SerializeToString,
            response_deserializer=proto_dot_queueservice_dot_v1_dot_request__response__pb2.DeleteFromDLQResponse.FromString,
            _registered_method=True,
        )
        self.PurgeDLQ = channel.unary_unary(
            "/chronoqueue.api.queueservice.v1.QueueService/PurgeDLQ",
            request_serializer=proto_dot_queueservice_dot_v1_dot_request__response__pb2.PurgeDLQRequest.SerializeToString,
            response_deserializer=proto_dot_queueservice_dot_v1_dot_request__response__pb2.PurgeDLQResponse.FromString,
            _registered_method=True,
        )
        self.GetDLQStats = channel.unary_unary(
            "/chronoqueue.api.queueservice.v1.QueueService/GetDLQStats",
            request_serializer=proto_dot_queueservice_dot_v1_dot_request__response__pb2.GetDLQStatsRequest.SerializeToString,
            response_deserializer=proto_dot_queueservice_dot_v1_dot_request__response__pb2.GetDLQStatsResponse.FromString,
            _registered_method=True,
        )
        self.ValidateCalendarSchedule = channel.unary_unary(
            "/chronoqueue.api.queueservice.v1.QueueService/ValidateCalendarSchedule",
            request_serializer=proto_dot_queueservice_dot_v1_dot_request__response__pb2.ValidateCalendarScheduleRequest.SerializeToString,
            response_deserializer=proto_dot_queueservice_dot_v1_dot_request__response__pb2.ValidateCalendarScheduleResponse.FromString,
            _registered_method=True,
        )
        self.PreviewCalendarSchedule = channel.unary_unary(
            "/chronoqueue.api.queueservice.v1.QueueService/PreviewCalendarSchedule",
            request_serializer=proto_dot_queueservice_dot_v1_dot_request__response__pb2.PreviewCalendarScheduleRequest.SerializeToString,
            response_deserializer=proto_dot_queueservice_dot_v1_dot_request__response__pb2.PreviewCalendarScheduleResponse.FromString,
            _registered_method=True,
        )
        self.RegisterSchema = channel.unary_unary(
            "/chronoqueue.api.queueservice.v1.QueueService/RegisterSchema",
            request_serializer=proto_dot_queueservice_dot_v1_dot_request__response__pb2.RegisterSchemaRequest.SerializeToString,
            response_deserializer=proto_dot_queueservice_dot_v1_dot_request__response__pb2.RegisterSchemaResponse.FromString,
            _registered_method=True,
        )
        self.GetSchema = channel.unary_unary(
            "/chronoqueue.api.queueservice.v1.QueueService/GetSchema",
            request_serializer=proto_dot_queueservice_dot_v1_dot_request__response__pb2.GetSchemaRequest.SerializeToString,
            response_deserializer=proto_dot_queueservice_dot_v1_dot_request__response__pb2.GetSchemaResponse.FromString,
            _registered_method=True,
        )
        self.ListSchemas = channel.unary_unary(
            "/chronoqueue.api.queueservice.v1.QueueService/ListSchemas",
            request_serializer=proto_dot_queueservice_dot_v1_dot_request__response__pb2.ListSchemasRequest.SerializeToString,
            response_deserializer=proto_dot_queueservice_dot_v1_dot_request__response__pb2.ListSchemasResponse.FromString,
            _registered_method=True,
        )
        self.DeleteSchema = channel.unary_unary(
            "/chronoqueue.api.queueservice.v1.QueueService/DeleteSchema",
            request_serializer=proto_dot_queueservice_dot_v1_dot_request__response__pb2.DeleteSchemaRequest.SerializeToString,
            response_deserializer=proto_dot_queueservice_dot_v1_dot_request__response__pb2.DeleteSchemaResponse.FromString,
            _registered_method=True,
        )
        self.ValidatePayload = channel.unary_unary(
            "/chronoqueue.api.queueservice.v1.QueueService/ValidatePayload",
            request_serializer=proto_dot_queueservice_dot_v1_dot_request__response__pb2.ValidatePayloadRequest.SerializeToString,
            response_deserializer=proto_dot_queueservice_dot_v1_dot_request__response__pb2.ValidatePayloadResponse.FromString,
            _registered_method=True,
        )


class QueueServiceServicer(object):
    """QueueService is the primary API for interacting with ChronoQueue.

    This service provides:
    - Queue lifecycle management
    - Message posting and consumption
    - Scheduled task automation
    - Dead letter queue handling
    - Schema-based validation

    Example - Basic message flow:
    1. CreateQueue: Set up a queue with retry/DLQ configuration
    2. PostMessage: Add messages to the queue
    3. GetNextMessage: Workers retrieve messages for processing
    4. AcknowledgeMessage: Mark message as successfully processed
    OR let lease expire → message returns to queue for retry
    5. After max_attempts exhausted → message moves to DLQ

    gRPC vs REST:
    - gRPC: Preferred for high-throughput, low-latency scenarios
    - REST: Convenient for browser/curl access, debugging, simple integrations

    Error handling:
    - Use gRPC status codes (InvalidArgument, NotFound, AlreadyExists, etc.)
    - Error details in status.Details() for validation errors
    ==================== Queue Management Operations ====================
    """

    def CreateQueue(self, request, context):
        """CreateQueue creates a new queue with specified configuration.

        Use to:
        - Define retry behavior (max_attempts, lease_duration)
        - Set up dead letter queue for failed messages
        - Configure priority handling
        - Enforce message schemas

        Example:
        POST /v1/queues
        {
        "queue": {
        "name": "order-processing",
        "metadata": {
        "default_max_attempts": 3,
        "lease_duration": "5m",
        "dead_letter_queue_name": "order-dlq",
        "auto_create_dlq": true
        }
        }
        }

        Returns: Queue details
        Errors:
        - AlreadyExists: Queue with this name exists
        - InvalidArgument: Invalid configuration (negative lease_duration, etc.)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def DeleteQueue(self, request, context):
        """DeleteQueue permanently deletes a queue and all its messages.

        WARNING: This operation is irreversible. All pending and running messages are lost.

        Use when:
        - Decommissioning a feature
        - Cleaning up test queues
        - Removing unused queues

        Best practice: Drain queue first (stop posting, wait for workers to finish).

        Example:
        DELETE /v1/queues/order-processing

        Returns: Empty response
        Errors:
        - NotFound: Queue doesn't exist
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def ListQueues(self, request, context):
        """ListQueues returns all queues in your ChronoQueue instance.

        Use for:
        - Monitoring dashboards
        - Queue discovery
        - Debugging

        Example:
        GET /v1/queues

        Returns: List of Queue objects with metadata
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def GetQueueState(self, request, context):
        """GetQueueState returns current queue statistics and health.

        Provides:
        - Message counts by state (PENDING, RUNNING, COMPLETED, ERRORED)
        - Rate metrics (messages/sec, processing time)
        - DLQ size

        Use for:
        - Health checks
        - Autoscaling decisions (scale workers based on PENDING count)
        - Alerting (high ERRORED count, DLQ growth)

        Example:
        GET /v1/queues/order-processing/state
        Response:
        {
        "pending_count": 150,
        "running_count": 10,
        "completed_count": 5420,
        "errored_count": 3,
        "dlq_count": 2
        }

        Returns: QueueState with counts and metrics
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def PostMessage(self, request, context):
        """==================== Message Operations ====================

        PostMessage adds a new message to a queue.

        Use for:
        - Asynchronous task execution
        - Event-driven workflows
        - Job scheduling
        - Load leveling

        Features:
        - Delayed execution (scheduled_time)
        - Priority ordering
        - Schema validation
        - Deduplication (idempotency_key)
        - Exclusive processing (exclusivity_key)

        Example - immediate execution:
        POST /v1/queues/order-processing/messages
        {
        "message": {
        "metadata": {
        "payload": {"data": "..."},
        "priority": 4
        }
        }
        }

        Example - delayed execution (send email in 1 hour):
        {
        "message": {
        "metadata": {
        "payload": {"data": "..."},
        "scheduled_time": "2024-12-01T15:00:00Z"
        }
        }
        }

        Returns: Message with assigned message_id
        Errors:
        - NotFound: Queue doesn't exist
        - InvalidArgument: Schema validation failed, invalid scheduled_time
        - AlreadyExists: Duplicate idempotency_key (within dedup window)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def PostMessagesBulk(self, request, context):
        """PostMessagesBulk posts multiple messages to a queue in a single operation.

        Supports two transaction modes:
        - ALL_OR_NOTHING: All messages succeed or all fail (atomic)
        - BEST_EFFORT: Independent processing, partial success allowed

        Limits:
        - Max 1000 messages per request
        - Max 1MB total payload size

        Errors:
        - NotFound: Queue doesn't exist
        - InvalidArgument: Too many messages, payload too large, invalid mode
        - FailedPrecondition: One or more messages failed in ALL_OR_NOTHING mode (entire batch rejected)

        Individual message errors are returned in the response with per-message error codes.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def GetNextMessage(self, request, context):
        """GetNextMessage retrieves the next available message for processing.

        This is the primary worker API. Call in a loop to continuously process messages.

        Behavior:
        - Returns highest priority PENDING message
        - Message moves to RUNNING state
        - Lease timer starts (worker has lease_duration to process)
        - If lease expires without ACK → message returns to PENDING for retry

        Concurrency:
        - Multiple workers can call simultaneously
        - Each worker gets a different message (no duplicates)
        - Use exclusivity_key for single-threaded processing of related messages

        Example worker loop:
        for {
        resp := client.GetNextMessage(ctx, &GetNextMessageRequest{
        QueueName: "order-processing",
        LeaseDuration: durationpb.New(5 * time.Minute),
        })
        if resp.Message == nil {
        time.Sleep(1 * time.Second)  // No messages available
        continue
        }

        err := processMessage(resp.Message)
        if err != nil {
        // Let lease expire → automatic retry
        continue
        }

        client.AcknowledgeMessage(ctx, &AcknowledgeMessageRequest{
        QueueName: "order-processing",
        MessageId: resp.Message.MessageId,
        })
        }

        Returns: Message (or empty if no messages available)
        Errors:
        - NotFound: Queue doesn't exist
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def AcknowledgeMessage(self, request, context):
        """AcknowledgeMessage marks a message as successfully processed.

        Call this after successfully processing a message retrieved by GetNextMessage.

        Effects:
        - Message moves to COMPLETED state
        - Message removed from queue
        - Queue stats updated

        Important: You must ACK within the lease_duration, or the message returns
        to PENDING and may be delivered to another worker.

        Example:
        POST /v1/queues/order-processing/messages/msg-123:acknowledge

        Returns: Empty response
        Errors:
        - NotFound: Message doesn't exist or already acknowledged
        - DeadlineExceeded: Lease already expired
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def CancelMessage(self, request, context):
        """CancelMessage cancels a pending message before it has been processed.

        Use when:
        - Business logic invalidates the need for a message (order cancelled, user unsubscribed)
        - Scheduled messages no longer needed (event rescheduled, task no longer relevant)
        - Cleanup operations (purge old scheduled notifications)

        Producer-side operation: Only messages in INVISIBLE or PENDING state can be cancelled.
        Messages already being processed (RUNNING) cannot be cancelled - use application-level
        cancellation logic instead.

        Effects:
        - Message moves to CANCELED state
        - Message removed from processing queue
        - Message retained based on retention policy (soft delete)
        - Queue stats updated

        Example - cancel scheduled reminder:
        POST /v1/queues/notifications/messages/reminder-456:cancel

        Example - cancel all pending messages for a user:
        foreach messageId in userMessages:
        CancelMessage(queueName, messageId)

        Returns: Empty response
        Errors:
        - NotFound: Message doesn't exist
        - FailedPrecondition: Message is RUNNING, COMPLETED, ERRORED, or already CANCELED
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def RenewMessageLease(self, request, context):
        """RenewMessageLease extends the processing time for a message.

        Use when:
        - Processing takes longer than expected
        - Long-running batch operations
        - External API calls with unpredictable latency

        Call periodically during processing to prevent lease expiration.

        Example pattern (heartbeat-style lease renewal):
        msg := getNextMessage()
        done := make(chan bool)

        go func() {
        ticker := time.NewTicker(leaseDuration / 2)
        defer ticker.Stop()
        for {
        select {
        case <-ticker.C:
        renewMessageLease(msg.MessageId)
        case <-done:
        return
        }
        }
        }()

        processMessage(msg)
        close(done)
        acknowledgeMessage(msg.MessageId)

        Returns: Updated message with new lease expiration
        Errors:
        - NotFound: Message doesn't exist or already completed
        - FailedPrecondition: Message not in RUNNING state
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def PeekQueueMessages(self, request, context):
        """PeekQueueMessages views messages without leasing them.

        Use for:
        - Debugging (inspect message payloads)
        - Monitoring (see what's pending)
        - Admin dashboards

        Does NOT:
        - Change message state
        - Create leases
        - Affect message ordering

        Example:
        GET /v1/queues/order-processing/messages:peek?count=10

        Returns: List of messages (up to requested count)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def SendMessageHeartBeat(self, request, context):
        """SendMessageHeartBeat indicates a worker is still processing a message.

        Alternative to RenewMessageLease with similar purpose but lighter weight.
        Useful for tracking worker health without extending lease.

        Example:
        POST /v1/queues/order-processing/messages:heartbeat
        {
        "message_ids": ["msg-123", "msg-456"]
        }

        Returns: Empty response
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def CreateSchedule(self, request, context):
        """==================== Schedule Management Operations ====================

        CreateSchedule creates a recurring message posting schedule.

        Use for:
        - Cron-style job scheduling (daily reports, hourly cleanup)
        - Business calendar scheduling (first business day of month)
        - Recurring notifications (reminders, alerts)
        - Periodic batch processing

        Supports:
        - Simple cron expressions: "0 9 * * 1-5" (weekdays at 9 AM)
        - Complex calendar rules: "last Friday of each quarter"
        - Timezone-aware scheduling
        - Holiday handling

        Example - daily report at 8 AM EST:
        POST /v1/schedules
        {
        "schedule": {
        "schedule_id": "daily-sales-report",
        "metadata": {
        "cron_schedule": "0 8 * * *",
        "timezone": "America/New_York",
        "queue_name": "reports",
        "payload": {...}
        }
        }
        }

        Returns: Created schedule with next_run time
        Errors:
        - AlreadyExists: schedule_id already in use
        - InvalidArgument: Invalid cron expression or calendar rule
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def DeleteSchedule(self, request, context):
        """DeleteSchedule permanently removes a schedule.

        Effects:
        - Schedule stops creating new messages
        - Existing messages already posted remain in queue
        - Schedule history is preserved

        Example:
        DELETE /v1/schedules/daily-sales-report

        Returns: Empty response
        Errors:
        - NotFound: Schedule doesn't exist
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def GetSchedule(self, request, context):
        """GetSchedule retrieves schedule details and current state.

        Returns:
        - Schedule configuration
        - Current state (SCHEDULED, PAUSED, CANCELED, ERRORED)
        - Next execution time
        - Last execution time
        - Execution count

        Example:
        GET /v1/schedules/daily-sales-report

        Returns: Schedule object
        Errors:
        - NotFound: Schedule doesn't exist
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def ListSchedules(self, request, context):
        """ListSchedules returns all schedules.

        Use for:
        - Admin dashboards
        - Monitoring active schedules
        - Discovering schedules

        Example:
        GET /v1/schedules

        Returns: List of Schedule objects
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def GetScheduleHistory(self, request, context):
        """GetScheduleHistory returns execution history for a schedule.

        Shows:
        - Past executions with timestamps
        - Messages created by each execution
        - Success/failure status

        Use for:
        - Debugging missed executions
        - Auditing schedule activity
        - Verifying schedule correctness

        Example:
        GET /v1/schedules/daily-sales-report/history

        Returns: ScheduleHistory with execution records
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def PauseSchedule(self, request, context):
        """PauseSchedule temporarily stops a schedule from creating messages.

        Use when:
        - Temporarily disabling a feature
        - During maintenance windows
        - Debugging issues

        Effects:
        - Schedule state → PAUSED
        - No new messages created
        - Can be resumed later with ResumeSchedule

        Example:
        POST /v1/schedules/daily-sales-report:pause

        Returns: Updated schedule
        Errors:
        - NotFound: Schedule doesn't exist
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def ResumeSchedule(self, request, context):
        """ResumeSchedule reactivates a paused schedule.

        Effects:
        - Schedule state → SCHEDULED
        - Resumes creating messages on next scheduled time
        - Does NOT backfill missed executions during pause

        Example:
        POST /v1/schedules/daily-sales-report:resume

        Returns: Updated schedule with next_run
        Errors:
        - NotFound: Schedule doesn't exist
        - FailedPrecondition: Schedule not in PAUSED state
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def GetDLQMessages(self, request, context):
        """==================== Dead Letter Queue Management ====================

        GetDLQMessages retrieves messages from a dead letter queue.

        Dead letter queues contain:
        - Messages that exhausted retry attempts
        - Messages that caused persistent errors
        - Messages rejected by workers

        Use for:
        - Investigating failures
        - Manual reprocessing after fixing bugs
        - Identifying systematic issues

        Example:
        GET /v1/dlq/order-dlq/messages?limit=50

        Returns: List of failed messages with error details
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def RequeueFromDLQ(self, request, context):
        """RequeueFromDLQ moves a message from DLQ back to its original queue.

        Use after:
        - Fixing bugs that caused failures
        - Resolving external service outages
        - Correcting data issues

        Effects:
        - Message removed from DLQ
        - Message added back to original queue as PENDING
        - attempts_left reset (or set to specified value)

        Example:
        POST /v1/dlq/order-dlq/messages/msg-123:requeue
        {
        "max_attempts": 3  // Give it 3 more tries
        }

        Returns: Requeued message
        Errors:
        - NotFound: Message not in DLQ
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def DeleteFromDLQ(self, request, context):
        """DeleteFromDLQ permanently removes a message from the DLQ.

        Use when:
        - Message is not recoverable
        - Data is no longer relevant
        - Cleaning up test data

        WARNING: This is permanent. Message cannot be recovered.

        Example:
        DELETE /v1/dlq/order-dlq/messages/msg-123

        Returns: Empty response
        Errors:
        - NotFound: Message not in DLQ
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def PurgeDLQ(self, request, context):
        """PurgeDLQ removes all messages from a dead letter queue.

        Use when:
        - Cleaning up after incident
        - Clearing test data
        - DLQ too large to manage individually

        WARNING: This is irreversible. All DLQ messages are permanently deleted.

        Example:
        POST /v1/dlq/order-dlq:purge

        Returns: Count of deleted messages
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def GetDLQStats(self, request, context):
        """GetDLQStats returns statistics about a dead letter queue.

        Provides:
        - Message count
        - Age of oldest message
        - Common error types
        - Failure rate trends

        Use for:
        - Monitoring DLQ health
        - Alerting on DLQ growth
        - Identifying systemic issues

        Example:
        GET /v1/dlq/order-dlq/stats

        Returns: DLQ statistics
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def ValidateCalendarSchedule(self, request, context):
        """==================== Calendar Schedule Operations ====================

        ValidateCalendarSchedule checks if a calendar schedule is valid.

        Validates:
        - Cron expression syntax
        - Calendar rule correctness
        - Timezone validity
        - Holiday rule logic

        Use before CreateSchedule to catch configuration errors.

        Example:
        POST /v1/calendar-schedules:validate
        {
        "calendar_schedule": {...}
        }

        Returns: Validation result with errors if invalid
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def PreviewCalendarSchedule(self, request, context):
        """PreviewCalendarSchedule shows next N execution times for a schedule.

        Use to:
        - Verify schedule behaves as expected
        - Test complex calendar rules
        - Confirm timezone handling
        - Preview holiday exceptions

        Example:
        POST /v1/calendar-schedules:preview
        {
        "calendar_schedule": {...},
        "count": 10  // Next 10 executions
        }

        Response:
        {
        "next_runs": [
        "2024-01-02T09:00:00Z",
        "2024-01-03T09:00:00Z",
        "2024-01-04T09:00:00Z",
        ...
        ]
        }

        Returns: List of upcoming execution timestamps
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def RegisterSchema(self, request, context):
        """==================== Schema Management Operations ====================

        RegisterSchema creates or updates a message validation schema.

        Use for:
        - Enforcing message structure
        - API contract validation
        - Data quality checks
        - Type safety

        Schema versioning:
        - Each schema has a schema_id and version number
        - Multiple versions can coexist
        - Queues reference schema_id (use highest active version)

        Example:
        POST /v1/schemas
        {
        "schema": {
        "schema_id": "order-schema",
        "version": 2,
        "content": "{...JSON Schema...}",
        "content_type": "json-schema"
        }
        }

        Returns: Registered schema
        Errors:
        - AlreadyExists: schema_id + version already exists
        - InvalidArgument: Invalid schema syntax
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def GetSchema(self, request, context):
        """GetSchema retrieves a specific schema version.

        Example:
        GET /v1/schemas/order-schema/versions/2

        Returns: Schema details
        Errors:
        - NotFound: Schema not found
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def ListSchemas(self, request, context):
        """ListSchemas returns all registered schemas.

        Use for:
        - Schema discovery
        - Admin dashboards
        - Schema management

        Example:
        GET /v1/schemas

        Returns: List of schemas (all versions)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def DeleteSchema(self, request, context):
        """DeleteSchema removes a schema version.

        Effects:
        - Schema version deleted
        - Queues using this schema will fail validation

        Best practice: Mark schema as inactive (is_active = false) instead
        of deleting to preserve validation history.

        Example:
        DELETE /v1/schemas/order-schema/versions/1

        Returns: Empty response
        Errors:
        - NotFound: Schema not found
        - FailedPrecondition: Schema in use by active queues
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def ValidatePayload(self, request, context):
        """ValidatePayload validates a payload against a schema without posting a message.

        Use for:
        - Pre-flight validation
        - Testing schema changes
        - Client-side validation
        - Development/debugging

        Example:
        POST /v1/schemas/order-schema/versions/2:validate
        {
        "payload": {
        "data": "{\"orderId\": \"ORD-123\", ...}"
        }
        }

        Returns: ValidationResult (valid=true or list of errors)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_QueueServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "CreateQueue": grpc.unary_unary_rpc_method_handler(
            servicer.CreateQueue,
            request_deserializer=proto_dot_queueservice_dot_v1_dot_request__response__pb2.CreateQueueRequest.FromString,
            response_serializer=proto_dot_queueservice_dot_v1_dot_request__response__pb2.CreateQueueResponse.SerializeToString,
        ),
        "DeleteQueue": grpc.unary_unary_rpc_method_handler(
            servicer.DeleteQueue,
            request_deserializer=proto_dot_queueservice_dot_v1_dot_request__response__pb2.DeleteQueueRequest.FromString,
            response_serializer=proto_dot_queueservice_dot_v1_dot_request__response__pb2.DeleteQueueResponse.SerializeToString,
        ),
        "ListQueues": grpc.unary_unary_rpc_method_handler(
            servicer.ListQueues,
            request_deserializer=proto_dot_queueservice_dot_v1_dot_request__response__pb2.ListQueuesRequest.FromString,
            response_serializer=proto_dot_queueservice_dot_v1_dot_request__response__pb2.ListQueuesResponse.SerializeToString,
        ),
        "GetQueueState": grpc.unary_unary_rpc_method_handler(
            servicer.GetQueueState,
            request_deserializer=proto_dot_queueservice_dot_v1_dot_request__response__pb2.GetQueueStateRequest.FromString,
            response_serializer=proto_dot_queueservice_dot_v1_dot_request__response__pb2.GetQueueStateResponse.SerializeToString,
        ),
        "PostMessage": grpc.unary_unary_rpc_method_handler(
            servicer.PostMessage,
            request_deserializer=proto_dot_queueservice_dot_v1_dot_request__response__pb2.PostMessageRequest.FromString,
            response_serializer=proto_dot_queueservice_dot_v1_dot_request__response__pb2.PostMessageResponse.SerializeToString,
        ),
        "PostMessagesBulk": grpc.unary_unary_rpc_method_handler(
            servicer.PostMessagesBulk,
            request_deserializer=proto_dot_queueservice_dot_v1_dot_request__response__pb2.PostMessagesBulkRequest.FromString,
            response_serializer=proto_dot_queueservice_dot_v1_dot_request__response__pb2.PostMessagesBulkResponse.SerializeToString,
        ),
        "GetNextMessage": grpc.unary_unary_rpc_method_handler(
            servicer.GetNextMessage,
            request_deserializer=proto_dot_queueservice_dot_v1_dot_request__response__pb2.GetNextMessageRequest.FromString,
            response_serializer=proto_dot_queueservice_dot_v1_dot_request__response__pb2.GetNextMessageResponse.SerializeToString,
        ),
        "AcknowledgeMessage": grpc.unary_unary_rpc_method_handler(
            servicer.AcknowledgeMessage,
            request_deserializer=proto_dot_queueservice_dot_v1_dot_request__response__pb2.AcknowledgeMessageRequest.FromString,
            response_serializer=proto_dot_queueservice_dot_v1_dot_request__response__pb2.AcknowledgeMessageResponse.SerializeToString,
        ),
        "CancelMessage": grpc.unary_unary_rpc_method_handler(
            servicer.CancelMessage,
            request_deserializer=proto_dot_queueservice_dot_v1_dot_request__response__pb2.CancelMessageRequest.FromString,
            response_serializer=proto_dot_queueservice_dot_v1_dot_request__response__pb2.CancelMessageResponse.SerializeToString,
        ),
        "RenewMessageLease": grpc.unary_unary_rpc_method_handler(
            servicer.RenewMessageLease,
            request_deserializer=proto_dot_queueservice_dot_v1_dot_request__response__pb2.RenewMessageLeaseRequest.FromString,
            response_serializer=proto_dot_queueservice_dot_v1_dot_request__response__pb2.RenewMessageLeaseResponse.SerializeToString,
        ),
        "PeekQueueMessages": grpc.unary_unary_rpc_method_handler(
            servicer.PeekQueueMessages,
            request_deserializer=proto_dot_queueservice_dot_v1_dot_request__response__pb2.PeekQueueMessagesRequest.FromString,
            response_serializer=proto_dot_queueservice_dot_v1_dot_request__response__pb2.PeekQueueMessagesResponse.SerializeToString,
        ),
        "SendMessageHeartBeat": grpc.unary_unary_rpc_method_handler(
            servicer.SendMessageHeartBeat,
            request_deserializer=proto_dot_queueservice_dot_v1_dot_request__response__pb2.SendMessageHeartBeatRequest.FromString,
            response_serializer=proto_dot_queueservice_dot_v1_dot_request__response__pb2.SendMessageHeartBeatResponse.SerializeToString,
        ),
        "CreateSchedule": grpc.unary_unary_rpc_method_handler(
            servicer.CreateSchedule,
            request_deserializer=proto_dot_queueservice_dot_v1_dot_request__response__pb2.CreateScheduleRequest.FromString,
            response_serializer=proto_dot_queueservice_dot_v1_dot_request__response__pb2.CreateScheduleResponse.SerializeToString,
        ),
        "DeleteSchedule": grpc.unary_unary_rpc_method_handler(
            servicer.DeleteSchedule,
            request_deserializer=proto_dot_queueservice_dot_v1_dot_request__response__pb2.DeleteScheduleRequest.FromString,
            response_serializer=proto_dot_queueservice_dot_v1_dot_request__response__pb2.DeleteScheduleResponse.SerializeToString,
        ),
        "GetSchedule": grpc.unary_unary_rpc_method_handler(
            servicer.GetSchedule,
            request_deserializer=proto_dot_queueservice_dot_v1_dot_request__response__pb2.GetScheduleRequest.FromString,
            response_serializer=proto_dot_queueservice_dot_v1_dot_request__response__pb2.GetScheduleResponse.SerializeToString,
        ),
        "ListSchedules": grpc.unary_unary_rpc_method_handler(
            servicer.ListSchedules,
            request_deserializer=proto_dot_queueservice_dot_v1_dot_request__response__pb2.ListSchedulesRequest.FromString,
            response_serializer=proto_dot_queueservice_dot_v1_dot_request__response__pb2.ListSchedulesResponse.SerializeToString,
        ),
        "GetScheduleHistory": grpc.unary_unary_rpc_method_handler(
            servicer.GetScheduleHistory,
            request_deserializer=proto_dot_queueservice_dot_v1_dot_request__response__pb2.GetScheduleHistoryRequest.FromString,
            response_serializer=proto_dot_queueservice_dot_v1_dot_request__response__pb2.GetScheduleHistoryResponse.SerializeToString,
        ),
        "PauseSchedule": grpc.unary_unary_rpc_method_handler(
            servicer.PauseSchedule,
            request_deserializer=proto_dot_queueservice_dot_v1_dot_request__response__pb2.PauseScheduleRequest.FromString,
            response_serializer=proto_dot_queueservice_dot_v1_dot_request__response__pb2.PauseScheduleResponse.SerializeToString,
        ),
        "ResumeSchedule": grpc.unary_unary_rpc_method_handler(
            servicer.ResumeSchedule,
            request_deserializer=proto_dot_queueservice_dot_v1_dot_request__response__pb2.ResumeScheduleRequest.FromString,
            response_serializer=proto_dot_queueservice_dot_v1_dot_request__response__pb2.ResumeScheduleResponse.SerializeToString,
        ),
        "GetDLQMessages": grpc.unary_unary_rpc_method_handler(
            servicer.GetDLQMessages,
            request_deserializer=proto_dot_queueservice_dot_v1_dot_request__response__pb2.GetDLQMessagesRequest.FromString,
            response_serializer=proto_dot_queueservice_dot_v1_dot_request__response__pb2.GetDLQMessagesResponse.SerializeToString,
        ),
        "RequeueFromDLQ": grpc.unary_unary_rpc_method_handler(
            servicer.RequeueFromDLQ,
            request_deserializer=proto_dot_queueservice_dot_v1_dot_request__response__pb2.RequeueFromDLQRequest.FromString,
            response_serializer=proto_dot_queueservice_dot_v1_dot_request__response__pb2.RequeueFromDLQResponse.SerializeToString,
        ),
        "DeleteFromDLQ": grpc.unary_unary_rpc_method_handler(
            servicer.DeleteFromDLQ,
            request_deserializer=proto_dot_queueservice_dot_v1_dot_request__response__pb2.DeleteFromDLQRequest.FromString,
            response_serializer=proto_dot_queueservice_dot_v1_dot_request__response__pb2.DeleteFromDLQResponse.SerializeToString,
        ),
        "PurgeDLQ": grpc.unary_unary_rpc_method_handler(
            servicer.PurgeDLQ,
            request_deserializer=proto_dot_queueservice_dot_v1_dot_request__response__pb2.PurgeDLQRequest.FromString,
            response_serializer=proto_dot_queueservice_dot_v1_dot_request__response__pb2.PurgeDLQResponse.SerializeToString,
        ),
        "GetDLQStats": grpc.unary_unary_rpc_method_handler(
            servicer.GetDLQStats,
            request_deserializer=proto_dot_queueservice_dot_v1_dot_request__response__pb2.GetDLQStatsRequest.FromString,
            response_serializer=proto_dot_queueservice_dot_v1_dot_request__response__pb2.GetDLQStatsResponse.SerializeToString,
        ),
        "ValidateCalendarSchedule": grpc.unary_unary_rpc_method_handler(
            servicer.ValidateCalendarSchedule,
            request_deserializer=proto_dot_queueservice_dot_v1_dot_request__response__pb2.ValidateCalendarScheduleRequest.FromString,
            response_serializer=proto_dot_queueservice_dot_v1_dot_request__response__pb2.ValidateCalendarScheduleResponse.SerializeToString,
        ),
        "PreviewCalendarSchedule": grpc.unary_unary_rpc_method_handler(
            servicer.PreviewCalendarSchedule,
            request_deserializer=proto_dot_queueservice_dot_v1_dot_request__response__pb2.PreviewCalendarScheduleRequest.FromString,
            response_serializer=proto_dot_queueservice_dot_v1_dot_request__response__pb2.PreviewCalendarScheduleResponse.SerializeToString,
        ),
        "RegisterSchema": grpc.unary_unary_rpc_method_handler(
            servicer.RegisterSchema,
            request_deserializer=proto_dot_queueservice_dot_v1_dot_request__response__pb2.RegisterSchemaRequest.FromString,
            response_serializer=proto_dot_queueservice_dot_v1_dot_request__response__pb2.RegisterSchemaResponse.SerializeToString,
        ),
        "GetSchema": grpc.unary_unary_rpc_method_handler(
            servicer.GetSchema,
            request_deserializer=proto_dot_queueservice_dot_v1_dot_request__response__pb2.GetSchemaRequest.FromString,
            response_serializer=proto_dot_queueservice_dot_v1_dot_request__response__pb2.GetSchemaResponse.SerializeToString,
        ),
        "ListSchemas": grpc.unary_unary_rpc_method_handler(
            servicer.ListSchemas,
            request_deserializer=proto_dot_queueservice_dot_v1_dot_request__response__pb2.ListSchemasRequest.FromString,
            response_serializer=proto_dot_queueservice_dot_v1_dot_request__response__pb2.ListSchemasResponse.SerializeToString,
        ),
        "DeleteSchema": grpc.unary_unary_rpc_method_handler(
            servicer.DeleteSchema,
            request_deserializer=proto_dot_queueservice_dot_v1_dot_request__response__pb2.DeleteSchemaRequest.FromString,
            response_serializer=proto_dot_queueservice_dot_v1_dot_request__response__pb2.DeleteSchemaResponse.SerializeToString,
        ),
        "ValidatePayload": grpc.unary_unary_rpc_method_handler(
            servicer.ValidatePayload,
            request_deserializer=proto_dot_queueservice_dot_v1_dot_request__response__pb2.ValidatePayloadRequest.FromString,
            response_serializer=proto_dot_queueservice_dot_v1_dot_request__response__pb2.ValidatePayloadResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "chronoqueue.api.queueservice.v1.QueueService", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers("chronoqueue.api.queueservice.v1.QueueService", rpc_method_handlers)


# This class is part of an EXPERIMENTAL API.
class QueueService(object):
    """QueueService is the primary API for interacting with ChronoQueue.

    This service provides:
    - Queue lifecycle management
    - Message posting and consumption
    - Scheduled task automation
    - Dead letter queue handling
    - Schema-based validation

    Example - Basic message flow:
    1. CreateQueue: Set up a queue with retry/DLQ configuration
    2. PostMessage: Add messages to the queue
    3. GetNextMessage: Workers retrieve messages for processing
    4. AcknowledgeMessage: Mark message as successfully processed
    OR let lease expire → message returns to queue for retry
    5. After max_attempts exhausted → message moves to DLQ

    gRPC vs REST:
    - gRPC: Preferred for high-throughput, low-latency scenarios
    - REST: Convenient for browser/curl access, debugging, simple integrations

    Error handling:
    - Use gRPC status codes (InvalidArgument, NotFound, AlreadyExists, etc.)
    - Error details in status.Details() for validation errors
    ==================== Queue Management Operations ====================
    """

    @staticmethod
    def CreateQueue(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/chronoqueue.api.queueservice.v1.QueueService/CreateQueue",
            proto_dot_queueservice_dot_v1_dot_request__response__pb2.CreateQueueRequest.SerializeToString,
            proto_dot_queueservice_dot_v1_dot_request__response__pb2.CreateQueueResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def DeleteQueue(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/chronoqueue.api.queueservice.v1.QueueService/DeleteQueue",
            proto_dot_queueservice_dot_v1_dot_request__response__pb2.DeleteQueueRequest.SerializeToString,
            proto_dot_queueservice_dot_v1_dot_request__response__pb2.DeleteQueueResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def ListQueues(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/chronoqueue.api.queueservice.v1.QueueService/ListQueues",
            proto_dot_queueservice_dot_v1_dot_request__response__pb2.ListQueuesRequest.SerializeToString,
            proto_dot_queueservice_dot_v1_dot_request__response__pb2.ListQueuesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def GetQueueState(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/chronoqueue.api.queueservice.v1.QueueService/GetQueueState",
            proto_dot_queueservice_dot_v1_dot_request__response__pb2.GetQueueStateRequest.SerializeToString,
            proto_dot_queueservice_dot_v1_dot_request__response__pb2.GetQueueStateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def PostMessage(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/chronoqueue.api.queueservice.v1.QueueService/PostMessage",
            proto_dot_queueservice_dot_v1_dot_request__response__pb2.PostMessageRequest.SerializeToString,
            proto_dot_queueservice_dot_v1_dot_request__response__pb2.PostMessageResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def PostMessagesBulk(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/chronoqueue.api.queueservice.v1.QueueService/PostMessagesBulk",
            proto_dot_queueservice_dot_v1_dot_request__response__pb2.PostMessagesBulkRequest.SerializeToString,
            proto_dot_queueservice_dot_v1_dot_request__response__pb2.PostMessagesBulkResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def GetNextMessage(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/chronoqueue.api.queueservice.v1.QueueService/GetNextMessage",
            proto_dot_queueservice_dot_v1_dot_request__response__pb2.GetNextMessageRequest.SerializeToString,
            proto_dot_queueservice_dot_v1_dot_request__response__pb2.GetNextMessageResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def AcknowledgeMessage(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/chronoqueue.api.queueservice.v1.QueueService/AcknowledgeMessage",
            proto_dot_queueservice_dot_v1_dot_request__response__pb2.AcknowledgeMessageRequest.SerializeToString,
            proto_dot_queueservice_dot_v1_dot_request__response__pb2.AcknowledgeMessageResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def CancelMessage(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/chronoqueue.api.queueservice.v1.QueueService/CancelMessage",
            proto_dot_queueservice_dot_v1_dot_request__response__pb2.CancelMessageRequest.SerializeToString,
            proto_dot_queueservice_dot_v1_dot_request__response__pb2.CancelMessageResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def RenewMessageLease(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/chronoqueue.api.queueservice.v1.QueueService/RenewMessageLease",
            proto_dot_queueservice_dot_v1_dot_request__response__pb2.RenewMessageLeaseRequest.SerializeToString,
            proto_dot_queueservice_dot_v1_dot_request__response__pb2.RenewMessageLeaseResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def PeekQueueMessages(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/chronoqueue.api.queueservice.v1.QueueService/PeekQueueMessages",
            proto_dot_queueservice_dot_v1_dot_request__response__pb2.PeekQueueMessagesRequest.SerializeToString,
            proto_dot_queueservice_dot_v1_dot_request__response__pb2.PeekQueueMessagesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def SendMessageHeartBeat(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/chronoqueue.api.queueservice.v1.QueueService/SendMessageHeartBeat",
            proto_dot_queueservice_dot_v1_dot_request__response__pb2.SendMessageHeartBeatRequest.SerializeToString,
            proto_dot_queueservice_dot_v1_dot_request__response__pb2.SendMessageHeartBeatResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def CreateSchedule(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/chronoqueue.api.queueservice.v1.QueueService/CreateSchedule",
            proto_dot_queueservice_dot_v1_dot_request__response__pb2.CreateScheduleRequest.SerializeToString,
            proto_dot_queueservice_dot_v1_dot_request__response__pb2.CreateScheduleResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def DeleteSchedule(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/chronoqueue.api.queueservice.v1.QueueService/DeleteSchedule",
            proto_dot_queueservice_dot_v1_dot_request__response__pb2.DeleteScheduleRequest.SerializeToString,
            proto_dot_queueservice_dot_v1_dot_request__response__pb2.DeleteScheduleResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def GetSchedule(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/chronoqueue.api.queueservice.v1.QueueService/GetSchedule",
            proto_dot_queueservice_dot_v1_dot_request__response__pb2.GetScheduleRequest.SerializeToString,
            proto_dot_queueservice_dot_v1_dot_request__response__pb2.GetScheduleResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def ListSchedules(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/chronoqueue.api.queueservice.v1.QueueService/ListSchedules",
            proto_dot_queueservice_dot_v1_dot_request__response__pb2.ListSchedulesRequest.SerializeToString,
            proto_dot_queueservice_dot_v1_dot_request__response__pb2.ListSchedulesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def GetScheduleHistory(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/chronoqueue.api.queueservice.v1.QueueService/GetScheduleHistory",
            proto_dot_queueservice_dot_v1_dot_request__response__pb2.GetScheduleHistoryRequest.SerializeToString,
            proto_dot_queueservice_dot_v1_dot_request__response__pb2.GetScheduleHistoryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def PauseSchedule(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/chronoqueue.api.queueservice.v1.QueueService/PauseSchedule",
            proto_dot_queueservice_dot_v1_dot_request__response__pb2.PauseScheduleRequest.SerializeToString,
            proto_dot_queueservice_dot_v1_dot_request__response__pb2.PauseScheduleResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def ResumeSchedule(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/chronoqueue.api.queueservice.v1.QueueService/ResumeSchedule",
            proto_dot_queueservice_dot_v1_dot_request__response__pb2.ResumeScheduleRequest.SerializeToString,
            proto_dot_queueservice_dot_v1_dot_request__response__pb2.ResumeScheduleResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def GetDLQMessages(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/chronoqueue.api.queueservice.v1.QueueService/GetDLQMessages",
            proto_dot_queueservice_dot_v1_dot_request__response__pb2.GetDLQMessagesRequest.SerializeToString,
            proto_dot_queueservice_dot_v1_dot_request__response__pb2.GetDLQMessagesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def RequeueFromDLQ(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/chronoqueue.api.queueservice.v1.QueueService/RequeueFromDLQ",
            proto_dot_queueservice_dot_v1_dot_request__response__pb2.RequeueFromDLQRequest.SerializeToString,
            proto_dot_queueservice_dot_v1_dot_request__response__pb2.RequeueFromDLQResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def DeleteFromDLQ(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/chronoqueue.api.queueservice.v1.QueueService/DeleteFromDLQ",
            proto_dot_queueservice_dot_v1_dot_request__response__pb2.DeleteFromDLQRequest.SerializeToString,
            proto_dot_queueservice_dot_v1_dot_request__response__pb2.DeleteFromDLQResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def PurgeDLQ(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/chronoqueue.api.queueservice.v1.QueueService/PurgeDLQ",
            proto_dot_queueservice_dot_v1_dot_request__response__pb2.PurgeDLQRequest.SerializeToString,
            proto_dot_queueservice_dot_v1_dot_request__response__pb2.PurgeDLQResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def GetDLQStats(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/chronoqueue.api.queueservice.v1.QueueService/GetDLQStats",
            proto_dot_queueservice_dot_v1_dot_request__response__pb2.GetDLQStatsRequest.SerializeToString,
            proto_dot_queueservice_dot_v1_dot_request__response__pb2.GetDLQStatsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def ValidateCalendarSchedule(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/chronoqueue.api.queueservice.v1.QueueService/ValidateCalendarSchedule",
            proto_dot_queueservice_dot_v1_dot_request__response__pb2.ValidateCalendarScheduleRequest.SerializeToString,
            proto_dot_queueservice_dot_v1_dot_request__response__pb2.ValidateCalendarScheduleResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def PreviewCalendarSchedule(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/chronoqueue.api.queueservice.v1.QueueService/PreviewCalendarSchedule",
            proto_dot_queueservice_dot_v1_dot_request__response__pb2.PreviewCalendarScheduleRequest.SerializeToString,
            proto_dot_queueservice_dot_v1_dot_request__response__pb2.PreviewCalendarScheduleResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def RegisterSchema(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/chronoqueue.api.queueservice.v1.QueueService/RegisterSchema",
            proto_dot_queueservice_dot_v1_dot_request__response__pb2.RegisterSchemaRequest.SerializeToString,
            proto_dot_queueservice_dot_v1_dot_request__response__pb2.RegisterSchemaResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def GetSchema(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/chronoqueue.api.queueservice.v1.QueueService/GetSchema",
            proto_dot_queueservice_dot_v1_dot_request__response__pb2.GetSchemaRequest.SerializeToString,
            proto_dot_queueservice_dot_v1_dot_request__response__pb2.GetSchemaResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def ListSchemas(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/chronoqueue.api.queueservice.v1.QueueService/ListSchemas",
            proto_dot_queueservice_dot_v1_dot_request__response__pb2.ListSchemasRequest.SerializeToString,
            proto_dot_queueservice_dot_v1_dot_request__response__pb2.ListSchemasResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def DeleteSchema(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/chronoqueue.api.queueservice.v1.QueueService/DeleteSchema",
            proto_dot_queueservice_dot_v1_dot_request__response__pb2.DeleteSchemaRequest.SerializeToString,
            proto_dot_queueservice_dot_v1_dot_request__response__pb2.DeleteSchemaResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def ValidatePayload(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/chronoqueue.api.queueservice.v1.QueueService/ValidatePayload",
            proto_dot_queueservice_dot_v1_dot_request__response__pb2.ValidatePayloadRequest.SerializeToString,
            proto_dot_queueservice_dot_v1_dot_request__response__pb2.ValidatePayloadResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )
