# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proto/schema/v1/schema.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'proto/schema/v1/schema.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1cproto/schema/v1/schema.proto\x12\x13nzovu.api.schema.v1\"\x9f\x02\n\x06Schema\x12\x11\n\tschema_id\x18\x01 \x01(\t\x12\x0f\n\x07version\x18\x02 \x01(\x05\x12\x0c\n\x04name\x18\x03 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x04 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x05 \x01(\t\x12\x14\n\x0c\x63ontent_type\x18\x06 \x01(\t\x12\x12\n\ncreated_at\x18\x07 \x01(\x03\x12\x12\n\nupdated_at\x18\x08 \x01(\x03\x12\x11\n\tis_active\x18\t \x01(\x08\x12;\n\x08metadata\x18\n \x03(\x0b\x32).nzovu.api.schema.v1.Schema.MetadataEntry\x1a/\n\rMetadataEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"\x98\x01\n\x10ValidationResult\x12\r\n\x05valid\x18\x01 \x01(\x08\x12\x34\n\x06\x65rrors\x18\x02 \x03(\x0b\x32$.nzovu.api.schema.v1.ValidationError\x12\x14\n\x0cvalidated_at\x18\x03 \x01(\x03\x12\x11\n\tschema_id\x18\x04 \x01(\t\x12\x16\n\x0eschema_version\x18\x05 \x01(\x05\"\xb9\x01\n\x0fValidationError\x12\r\n\x05\x66ield\x18\x01 \x01(\t\x12\x12\n\nerror_code\x18\x02 \x01(\t\x12\x0f\n\x07message\x18\x03 \x01(\t\x12\x42\n\x07\x64\x65tails\x18\x04 \x03(\x0b\x32\x31.nzovu.api.schema.v1.ValidationError.DetailsEntry\x1a.\n\x0c\x44\x65tailsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01*\xef\x02\n\tErrorCode\x12\x11\n\rUNKNOWN_ERROR\x10\x00\x12\x1a\n\x16REQUIRED_FIELD_MISSING\x10\x01\x12\x10\n\x0cINVALID_TYPE\x10\x02\x12\x12\n\x0eINVALID_FORMAT\x10\x03\x12\x14\n\x10PATTERN_MISMATCH\x10\x04\x12\x16\n\x12VALUE_OUT_OF_RANGE\x10\x05\x12\x18\n\x14\x41RRAY_LENGTH_INVALID\x10\x06\x12\x1d\n\x19OBJECT_PROPERTIES_INVALID\x10\x07\x12%\n!ADDITIONAL_PROPERTIES_NOT_ALLOWED\x10\x08\x12\x16\n\x12\x45NUM_VALUE_INVALID\x10\t\x12\x14\n\x10SCHEMA_NOT_FOUND\x10\n\x12\x18\n\x14\x43ONTENT_TYPE_INVALID\x10\x0b\x12\x19\n\x15PAYLOAD_SIZE_EXCEEDED\x10\x0c\x12\x1c\n\x18SCHEMA_VALIDATION_FAILED\x10\rB0Z.github.com/adrien19/nzovu/api/schema/v1;schemab\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'nzovu.api.schema.v1.schema_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z.github.com/adrien19/nzovu/api/schema/v1;schema'
  _globals['_SCHEMA_METADATAENTRY']._loaded_options = None
  _globals['_SCHEMA_METADATAENTRY']._serialized_options = b'8\001'
  _globals['_VALIDATIONERROR_DETAILSENTRY']._loaded_options = None
  _globals['_VALIDATIONERROR_DETAILSENTRY']._serialized_options = b'8\001'
  _globals['_ERRORCODE']._serialized_start=687
  _globals['_ERRORCODE']._serialized_end=1054
  _globals['_SCHEMA']._serialized_start=54
  _globals['_SCHEMA']._serialized_end=341
  _globals['_SCHEMA_METADATAENTRY']._serialized_start=294
  _globals['_SCHEMA_METADATAENTRY']._serialized_end=341
  _globals['_VALIDATIONRESULT']._serialized_start=344
  _globals['_VALIDATIONRESULT']._serialized_end=496
  _globals['_VALIDATIONERROR']._serialized_start=499
  _globals['_VALIDATIONERROR']._serialized_end=684
  _globals['_VALIDATIONERROR_DETAILSENTRY']._serialized_start=638
  _globals['_VALIDATIONERROR_DETAILSENTRY']._serialized_end=684
# @@protoc_insertion_point(module_scope)
